name: t5
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=20.1
  - pytorch=1.6.0
  - python=3.8
  - torchvision=0.7.0
  - cudatoolkit=10.2
  - pip:
    - Flask==1.1.2
    - gunicorn==20.0.4
    - pytorch-lightning==0.8.1
    - transformers==3.0.2
